export {default as chevronRight}  from './chevron-right.svg'
export {default as chevronLeft}  from './chevron-left.svg'
export {default as dashCircleFill}  from './dash-circle-fill.svg'
export {default as plusCircleFill}  from './plus-circle-fill.svg'
export {default as starFill}  from './star-fill.svg'
export {default as starNoFill}  from './star.svg'
export {default as chevronDoubleRight}  from './chevron-double-right.svg'
export {default as toBack} from './return-arrow.svg'